### ISSUE TITLE
add slots

### ISSUE THREAD

**Issue by helish88** [uewquewqueqwue/Yandex-Music-Ym-Handler#9]
you should add [slots](https://wiki.python.org/moin/UsingSlots) for classes

**Comment by ov3rwrite** [comment]
Why so? They do definitely increase the performance, but just slightly, for me. I don't really like __slots__, because you have to pass attribute names in them as strings, which doesn't look really clean. You can forget to change the name of an attribute and still have the old name in slots. Even modern IDE's don't change them after rename, as I remember. I think it shouldn't be an issue and you should leave it optional to the author.
